version: '3.9'

services:
  node_app:
    container_name: node_app
    build: .
    image: daohuytuan/menloone-test-be
    ports:
      - '3000:3000'
    environment:
      - PG_DB=node_pg_db
      - PG_USER=zyye
      - PG_PASSWORD=123123
      - PG_HOST=node_db
    restart: always
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=node_pg_db
      - POSTGRES_USER=zyye
      - POSTGRES_PASSWORD=123123
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
